using System;
using System.Collections.Generic;

namespace MoodleDbSimplificator.MoodleDb.V39.Entities;

/// <summary>
/// An information about autogenerated parts of symbols, that em
/// </summary>
public partial class MdlBlockFormalLangsDscPart
{
    public long Id { get; set; }

    public string Tablename { get; set; } = null!;

    public long Tableid { get; set; }

    public long Number { get; set; }

    public long Position { get; set; }

    public string Description { get; set; } = null!;
}
